version: '3'
services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env